#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Taken from: https://gist.github.com/dahjelle/8ddedf0aebd488208a9a7c829f19b9e8 with slight modifications
node_modules/.bin/prettier --write .

for file in $(git diff --cached --name-only | grep -E '\.(js|jsx|ts|tsx|json)$')
do
  git show ":$file" | node_modules/.bin/eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0 ]; then
    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run lint."
    exit 1 # exit with failure status
  fi
done
